### ISSUE TITLE
Error messaging 

### ISSUE THREAD

**Issue by chadtilbury** [00010111/gMetaDataParse#1]
It doesn't look like there is error handling if a user forgets to add the -c argument.  Maybe an error or a default file name using date/time (with a message)?

**Comment by 00010111** [comment]
should be fixed with current update:
Version 0.0502:

    Fix issue 1
        If neither json,csv,gui or verbose is choosen as output, gMetaDataParse will fall back to write csv output to local directory with a filename like: %Y%m%d_%H%M%S_output.csv
    improved error handling if database or cache dir are not found

(sorry that it tool so long... spare time projects without spare time move slowly ;))
